<a href="https://colab.research.google.com/github/otionrec/.github-workflows/blob/master/Great_Learning_Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# NumPy supports only homogenoue data types
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
randaom_print = np.random.randint(0,100,(4,4))
randaom_print

array([[70, 26, 75, 79],
       [88, 92, 70, 79],
       [74, 38, 83, 29],
       [19, 79, 59, 76]])

In [ ]:
randaom_print2 = np.random.randint(0,100,10)
randaom_print2

array([71, 80, 88, 58, 28, 46, 80, 88,  6, 26])

In [ ]:
numbers = np.arange(1,26).reshape(5,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
numbers[4][3] = 99
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 99, 25]])

In [ ]:
numbers[numbers%2==0] = 10
numbers

array([[ 1, 10,  3, 10,  5],
       [10,  7, 10,  9, 10],
       [11, 10, 13, 10, 15],
       [10, 17, 10, 19, 10],
       [21, 10, 23, 99, 25]])

In [ ]:
numbers = np.arange(10).reshape(2,-1)
numbers

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
numbers = np.arange(10).reshape(5,-1)
numbers

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
x = np.array([10,6,30,45])
y = np.array([36,85,10,2,7,30])
np.intersect1d(x,y)

array([10, 30])

In [ ]:
import pandas as pd
sample_dict = {'x':1, 'y':2, 'z':3}
pd.Series(sample_dict)

x    1
y    2
z    3
dtype: int64

In [ ]:
sample_series = pd.Series(list('12k45'))
sample_series.name = 'numbers'
sample_series.head()

0    1
1    2
2    k
3    4
4    5
Name: numbers, dtype: object

In [ ]:
sample_series = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
sample_series.value_counts()

3    2
5    2
1    1
2    1
4    1
6    1
7    1
8    1
9    1
Name: count, dtype: int64

In [ ]:
first_series = pd.Series([1,2,3,4,6])
second_series = pd.Series([5,6,7,8])
pd.Series(np.union1d(first_series,second_series))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
first_series = pd.Series([1,2,3,4,6])
second_series = pd.Series([5,6,7,8])
first_series[first_series.isin(second_series)]

4    6
dtype: int64

In [ ]:
first_series = pd.Series([1,2,3,4,6])
second_series = pd.Series([5,6,7,8])
first_series[~first_series.isin(second_series)]
# tilde reverses the output. thus playing a not role here

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
# converting numpy array into a pandas data frame
sample_series = pd.Series(np.random.randint(1,20,25))
pd.DataFrame(sample_series.values.reshape(5,5))


0   1   2   3   4
0   5  14   2  11  12
1   6  17  19   8   5
2  17   3  16  11  15
3   4  14   1  19  13
4   9   1   5  19  13

In [ ]:
names = np.array(['ram','ma','ri','shi'])
names[-1]

'shi'

In [ ]:
names = np.array(['ram','ma','ri','shi'])
names[:-1]

array(['ram', 'ma', 'ri'], dtype='<U3')

In [ ]:
names = np.array(['ram','ma','ri','shi'])
names[::-1]

array(['shi', 'ri', 'ma', 'ram'], dtype='<U3')