<a href="https://colab.research.google.com/github/otionrec/.github-workflows/blob/master/Module4_NumPy_and_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
- Means Numerical Python
- Efficient interface to store and manipulate data
- Core of almost all the data science tools in python
- Numpy is used to create and manipulate arrays
- Data is mostly stored in arrays before fed to the ML algorithms



In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
# Numpy Arrays

np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [ ]:
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [ ]:
np.array([[1,2,3], [4,5,6], [7,8,9]], np.float32)  #dtype = 'float32'

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.random((3,3))

array([[0.93441946, 0.2455096 , 0.74097505],
       [0.60097965, 0.33962189, 0.40331701],
       [0.20102773, 0.10004872, 0.64213964]])

# Attributes of Numpy Arrays
- Dimension: 1D, 2D, 3D etc.
- Shape: #dimension, #rows, #columns
- Size: #dimension x #rows x #columns

In [ ]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[6, 9, 0, 0, 4],
        [5, 7, 9, 4, 3],
        [3, 1, 7, 9, 6],
        [9, 6, 1, 4, 4]],

       [[1, 9, 4, 9, 9],
        [4, 5, 4, 5, 5],
        [5, 0, 2, 8, 6],
        [4, 2, 4, 2, 9]],

       [[5, 8, 8, 5, 1],
        [8, 2, 1, 5, 2],
        [0, 5, 8, 4, 5],
        [5, 9, 1, 0, 0]]])

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [ ]:
np.array([[[1,2],[3,4]],
          [[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
x = np.ones((4,3,2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
x[1,2,1]

1.0

In [ ]:
a = np.array([1,2,3,4,5,6])
a
b = a[3:]
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
len(a.shape)

2

In [ ]:
np.empty(2)

array([2.00000000e+000, 6.95307308e-310])

In [ ]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0,10,5) #num=5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
d = np.array([[1,4,3,7],[5,6,2,11],[8,10,9,12]])
d

array([[ 1,  4,  3,  7],
       [ 5,  6,  2, 11],
       [ 8, 10,  9, 12]])

In [ ]:
np.partition(d,2)

array([[ 1,  3,  4,  7],
       [ 2,  5,  6, 11],
       [ 8,  9, 10, 12]])

In [ ]:
d[1,3], d[1,1] = 0, 0
d

array([[ 1,  4,  3,  7],
       [ 5,  0,  2,  0],
       [ 8, 10,  9, 12]])

In [ ]:
b = a.reshape(2,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# Similar to the above
c = np.reshape(a, (2,6), order='C') # newshape=(2,6)
# order is the type of indexing to be used, whether C or Fortran
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
c[-1,3]

10

# Slicing
X[start:end:step]

In [ ]:
x = np.arange(10)

x[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[4:7]

array([4, 5, 6])

In [ ]:
x[9:1:-2]

array([9, 7, 5, 3])

In [ ]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[8, 4, 9, 1],
       [1, 8, 3, 5],
       [3, 6, 4, 6]])

In [ ]:
x2[:2, :3] # two rows, three columns

array([[8, 4, 9],
       [1, 8, 3]])

In [ ]:
x2[:3, ::2] # all rows, every other column

array([[8, 9],
       [1, 3],
       [3, 4]])

# Computation on NumPy Arrays

Vectorized Operations vs Loops

- Python loops slower
- Performing operations on large arrays becomes costly
- NumPy provides a vectorized approach using Ufuncs
-Faster execution

# Broadcasting
- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on the its leading(left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the size disagree and neither is equal to 1, an error is raised.

# Lesson Summary
